# Week 1


## Pytorch

In [1]:
!pip uninstall --yes torch torchaudio torchvision torchdata torchtext
!pip install torch torchaudio torchvision torchdata torchtext

Found existing installation: torch 2.10.0+cu128
Uninstalling torch-2.10.0+cu128:
  Successfully uninstalled torch-2.10.0+cu128
Found existing installation: torchaudio 2.10.0+cu128
Uninstalling torchaudio-2.10.0+cu128:
  Successfully uninstalled torchaudio-2.10.0+cu128
Found existing installation: torchvision 0.25.0+cu128
Uninstalling torchvision-0.25.0+cu128:
  Successfully uninstalled torchvision-0.25.0+cu128
Found existing installation: torchdata 0.11.0
Uninstalling torchdata-0.11.0:
  Successfully uninstalled torchdata-0.11.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 530.7/530.7 MB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.1/366.1 MB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.9/169.9 MB 15.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.5/196.5 MB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 MB 41.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 MB 2.7 MB

In [2]:
import numpy as np
import torch

data = np.array([1,2,4,5,6,6])
data

array([1, 2, 4, 5, 6, 6])

In [3]:
tensor_data = torch.from_numpy(data)
tensor_data

tensor([1, 2, 4, 5, 6, 6])

In [4]:
x_ones = torch.ones_like(tensor_data,dtype = torch.float)
x_ones

tensor([1., 1., 1., 1., 1., 1.])

In [5]:
x_rand = torch.randn_like(tensor_data,dtype = torch.float)
x_rand

tensor([-0.4019, -1.6149, -1.0303, -0.3755,  1.1386,  0.8618])

In [6]:
shape = (4,5)

tensor_ones = torch.ones(shape,dtype=torch.float64)
tensor_zeros = torch.zeros(shape)
tensor_rand = torch.rand(shape,dtype=torch.float64)

tensor_rand

tensor([[0.9338, 0.8950, 0.3494, 0.0308, 0.4540],
        [0.8653, 0.7992, 0.3565, 0.8612, 0.8142],
        [0.1852, 0.4699, 0.9855, 0.4266, 0.7466],
        [0.6412, 0.1151, 0.0307, 0.9976, 0.9564]], dtype=torch.float64)

In [7]:
# attributes of tensors

tensor_rand.shape
tensor_rand.dtype
tensor_rand.device

device(type='cpu')

In [8]:
if torch.accelerator.is_available():
  print(torch.accelerator.current_accelerator())
  tensor_rand.to(torch.accelerator.current_accelerator())
tensor_rand.device

cuda


device(type='cpu')

In [9]:
tensor_rand


tensor([[0.9338, 0.8950, 0.3494, 0.0308, 0.4540],
        [0.8653, 0.7992, 0.3565, 0.8612, 0.8142],
        [0.1852, 0.4699, 0.9855, 0.4266, 0.7466],
        [0.6412, 0.1151, 0.0307, 0.9976, 0.9564]], dtype=torch.float64)

In [10]:
tensor_rand[...,0]


tensor([0.9338, 0.8653, 0.1852, 0.6412], dtype=torch.float64)

In [11]:
res = torch.cat([tensor_rand, tensor_ones], dim = -1)
res

tensor([[0.9338, 0.8950, 0.3494, 0.0308, 0.4540, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000],
        [0.8653, 0.7992, 0.3565, 0.8612, 0.8142, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000],
        [0.1852, 0.4699, 0.9855, 0.4266, 0.7466, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000],
        [0.6412, 0.1151, 0.0307, 0.9976, 0.9564, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000]], dtype=torch.float64)

In [12]:
res = torch.stack([tensor_rand,tensor_ones],dim = 2)
res.shape

torch.Size([4, 5, 2])

In [13]:
x = torch.randn(shape)
x

tensor([[ 0.6394, -0.7516,  0.4721, -0.0507,  0.8244],
        [-1.7165,  2.2051,  0.2313,  2.6349,  0.8069],
        [ 0.8682, -0.2504,  0.4525,  1.4587, -1.3779],
        [ 1.1811, -0.1199,  3.1121, -0.1081, -0.0824]])

In [14]:
y = torch.rand_like(x)
y

tensor([[0.8518, 0.5876, 0.1126, 0.8093, 0.5915],
        [0.9382, 0.9912, 0.7852, 0.8867, 0.7631],
        [0.2738, 0.5420, 0.6143, 0.4992, 0.4114],
        [0.6793, 0.8362, 0.9409, 0.7344, 0.0961]])

In [15]:
z = torch.cat([x,y],dim =1)
print(z)
print(z.shape)
a = torch.stack([x,y],dim = 1)
print(a)
print(a.shape)

tensor([[ 0.6394, -0.7516,  0.4721, -0.0507,  0.8244,  0.8518,  0.5876,  0.1126,
          0.8093,  0.5915],
        [-1.7165,  2.2051,  0.2313,  2.6349,  0.8069,  0.9382,  0.9912,  0.7852,
          0.8867,  0.7631],
        [ 0.8682, -0.2504,  0.4525,  1.4587, -1.3779,  0.2738,  0.5420,  0.6143,
          0.4992,  0.4114],
        [ 1.1811, -0.1199,  3.1121, -0.1081, -0.0824,  0.6793,  0.8362,  0.9409,
          0.7344,  0.0961]])
torch.Size([4, 10])
tensor([[[ 0.6394, -0.7516,  0.4721, -0.0507,  0.8244],
         [ 0.8518,  0.5876,  0.1126,  0.8093,  0.5915]],

        [[-1.7165,  2.2051,  0.2313,  2.6349,  0.8069],
         [ 0.9382,  0.9912,  0.7852,  0.8867,  0.7631]],

        [[ 0.8682, -0.2504,  0.4525,  1.4587, -1.3779],
         [ 0.2738,  0.5420,  0.6143,  0.4992,  0.4114]],

        [[ 1.1811, -0.1199,  3.1121, -0.1081, -0.0824],
         [ 0.6793,  0.8362,  0.9409,  0.7344,  0.0961]]])
torch.Size([4, 2, 5])


### Products

In [16]:
tensor_rand,tensor_ones

(tensor([[0.9338, 0.8950, 0.3494, 0.0308, 0.4540],
         [0.8653, 0.7992, 0.3565, 0.8612, 0.8142],
         [0.1852, 0.4699, 0.9855, 0.4266, 0.7466],
         [0.6412, 0.1151, 0.0307, 0.9976, 0.9564]], dtype=torch.float64),
 tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]], dtype=torch.float64))

In [17]:
tensor_prod = tensor_rand @ tensor_ones.T
print(tensor_prod)
print(tensor_prod.shape)

tensor([[2.6629, 2.6629, 2.6629, 2.6629],
        [3.6963, 3.6963, 3.6963, 3.6963],
        [2.8139, 2.8139, 2.8139, 2.8139],
        [2.7409, 2.7409, 2.7409, 2.7409]], dtype=torch.float64)
torch.Size([4, 4])


In [18]:
tensor_prod = torch.matmul(tensor_rand,tensor_ones.transpose(0,1))
print(tensor_prod)
print(tensor_prod.shape)

tensor([[2.6629, 2.6629, 2.6629, 2.6629],
        [3.6963, 3.6963, 3.6963, 3.6963],
        [2.8139, 2.8139, 2.8139, 2.8139],
        [2.7409, 2.7409, 2.7409, 2.7409]], dtype=torch.float64)
torch.Size([4, 4])


In [19]:
x = torch.ones((4,4))
y.shape

start = time.perf_counter()
for i in range(4):
  for j in range(4):

    for k in range(5):

      x[i][j] += tensor_rand[i][k] * y[k][j]

end = time.perf_counter()
print(end-start)

print(x)
print(x.shape)

NameError: name 'time' is not defined

In [20]:
x = tensor_rand * y
print(x)
print(x.shape)

tensor([[0.7954, 0.5258, 0.0393, 0.0249, 0.2685],
        [0.8118, 0.7922, 0.2799, 0.7636, 0.6213],
        [0.0507, 0.2547, 0.6054, 0.2130, 0.3072],
        [0.4355, 0.0963, 0.0289, 0.7326, 0.0919]], dtype=torch.float64)
torch.Size([4, 5])


In [21]:
y

tensor([[0.8518, 0.5876, 0.1126, 0.8093, 0.5915],
        [0.9382, 0.9912, 0.7852, 0.8867, 0.7631],
        [0.2738, 0.5420, 0.6143, 0.4992, 0.4114],
        [0.6793, 0.8362, 0.9409, 0.7344, 0.0961]])

In [22]:
import time

start  = time.perf_counter()
# tensor_rand.mul(y)
x = tensor_rand * y
# x = torch.mul(tensor_rand,y)
end= time.perf_counter()
print(end-start)
x

0.0006004550000398012


tensor([[0.7954, 0.5258, 0.0393, 0.0249, 0.2685],
        [0.8118, 0.7922, 0.2799, 0.7636, 0.6213],
        [0.0507, 0.2547, 0.6054, 0.2130, 0.3072],
        [0.4355, 0.0963, 0.0289, 0.7326, 0.0919]], dtype=torch.float64)

In [23]:
start = time.perf_counter()
x= torch.ones_like(y)
for  i in range(tensor_rand.shape[0]):
  for j in range(tensor_rand.shape[1]):
    x[i][j]=tensor_rand[i][j]*y[i][j]
end = time.perf_counter()
print(end-start)
x

0.002092425999990155


tensor([[0.7954, 0.5258, 0.0393, 0.0249, 0.2685],
        [0.8118, 0.7922, 0.2799, 0.7636, 0.6213],
        [0.0507, 0.2547, 0.6054, 0.2130, 0.3072],
        [0.4355, 0.0963, 0.0289, 0.7326, 0.0919]])

In [24]:
print(tensor_rand)
print(tensor_rand.sub_(10))
# tensor_rand.t_()
tensor_rand.copy_(y)

tensor([[0.9338, 0.8950, 0.3494, 0.0308, 0.4540],
        [0.8653, 0.7992, 0.3565, 0.8612, 0.8142],
        [0.1852, 0.4699, 0.9855, 0.4266, 0.7466],
        [0.6412, 0.1151, 0.0307, 0.9976, 0.9564]], dtype=torch.float64)
tensor([[-9.0662, -9.1050, -9.6506, -9.9692, -9.5460],
        [-9.1347, -9.2008, -9.6435, -9.1388, -9.1858],
        [-9.8148, -9.5301, -9.0145, -9.5734, -9.2534],
        [-9.3588, -9.8849, -9.9693, -9.0024, -9.0436]], dtype=torch.float64)


tensor([[0.8518, 0.5876, 0.1126, 0.8093, 0.5915],
        [0.9382, 0.9912, 0.7852, 0.8867, 0.7631],
        [0.2738, 0.5420, 0.6143, 0.4992, 0.4114],
        [0.6793, 0.8362, 0.9409, 0.7344, 0.0961]], dtype=torch.float64)

### Autograd

In [25]:
x = torch.randn((4,3))
y = torch.rand((4,1)) # Changed to torch.rand for targets between 0 and 1
w = torch.ones((3,1),requires_grad = True)
b = torch.ones((4,1),requires_grad= True)

z = x@w + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)
loss

tensor(0.9626, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [26]:
loss.backward(retain_graph=True)
print(w.grad)
print(b.grad)


tensor([[0.0472],
        [0.2829],
        [0.1985]])
tensor([[ 0.1189],
        [ 0.0251],
        [-0.1496],
        [ 0.0638]])


In [27]:
learning_rate = 0.1 # Increased learning rate

with torch.no_grad():
  w.sub_(learning_rate * w.grad)
  b.sub_(learning_rate * b.grad)
  w.grad.zero_()
  b.grad.zero_()
  loss.backward(retain_graph=True)
  print(w.grad)
  print(b.grad)


z = x@w + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)
loss

tensor([[0.0472],
        [0.2829],
        [0.1985]])
tensor([[ 0.1189],
        [ 0.0251],
        [-0.1496],
        [ 0.0638]])


tensor(0.9464, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [28]:
z  = x@w + b
z,y

(tensor([[ 0.7347],
         [ 5.1735],
         [-1.6010],
         [ 1.7832]], grad_fn=<AddBackward0>),
 tensor([[0.2025],
         [0.8944],
         [0.7557],
         [0.6035]]))

In [29]:
from torchviz import make_dot

make_dot(loss, {'w':w,'b':b})

ModuleNotFoundError: No module named 'torchviz'

In [30]:
import sklearn
data = sklearn.datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [31]:
X = data['data']
y = data['target']
X.shape, y.shape

((150, 4), (150,))

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [33]:
import math
class LinearClassification(torch.nn.Module):
  def __init__(self,input_dim, output_dim):

    super().__init__()
    std = math.sqrt(1/(input_dim+output_dim))

    self.weight = torch.nn.Parameter(torch.nn.init.trunc_normal_(torch.empty(output_dim,input_dim),std= std,a = -3*std,b = 3*std),requires_grad = True)
    self.bias = torch.nn.Parameter(torch.nn.init.trunc_normal_(torch.empty(output_dim), std=std, a= -1*std,b = std),requires_grad=True)

  def forward(self,x):
    return x@self.weight.T + self.bias



In [34]:
def softmax(x,dim = -1):
  x_max = torch.max(x,dim= dim ,keepdim= True)[0]
  rescaled = x - x_max
  exp_rescaled = torch.exp(rescaled)
  exp_sum = torch.sum(exp_rescaled,dim = dim,keepdim =True)
  return exp_rescaled/exp_sum

def log_softmax(x,dim = -1):
  x_max = torch.max(x,dim= dim ,keepdim= True)[0]
  rescaled = x - x_max
  exp_rescaled = torch.exp(rescaled)
  exp_sum = torch.sum(exp_rescaled,dim = dim,keepdim =True)
  return rescaled - torch.log(exp_sum)


def cross_entropy(inputs,targets):
  negative_logits = -log_softmax(inputs,dim = -1)
  return torch.mean(torch.gather(negative_logits,-1, targets.unsqueeze(-1)))

def clip_gradient(parameters,max_norm):
  grads= [p.grad for p in parameters if p.grad is not None]
  if not grads:
      return

  norm = torch.tensor(0.0 , device = grads[0].device)

  for g in grads:

    norm+= torch.sum(g**2)

  norm = torch.sqrt(norm)


  clip_coeff= min(1.0, max_norm/(norm.item()+1e-6))

  for g in grads:
    g.mul_(clip_coeff)

In [35]:
def get_cosine_lr(it, warmup_iters, cosine_iters,min_learning_rate, max_learning_rate):

  if it < warmup_iters:
    return max_learning_rate* (it/warmup_iters)
  if it > cosine_iters:
    return min_learning_rate

  decay =(it-warmup_iters)/(cosine_iters-warmup_iters)
  decay_rate = 0.5*(1+math.cos(math.pi*decay))
  return min_learning_rate+decay_rate*(max_learning_rate-min_learning_rate)


In [36]:
from __future__ import annotations
from typing import Callable

class AdamW(torch.optim.Optimizer):
  def __init__(self, params, lr = 1e-3, betas = (0.9,0.999), eps = 1e-8, weight_decay = 0.0):
    defaults = dict(lr = lr, betas = betas, eps = eps, weight_decay = weight_decay)
    super().__init__(params,defaults)

  def step(self, closure: Callable | None =None):

    loss = None
    if not closure is None:
      loss = closure()

    for group in self.param_groups:
      for p in group['params']:
        if p.grad is None:
          continue
        grad = p.grad.data

        if grad.is_sparse:
          raise RuntimeError('AdamW does not support sparse gradients')

        # Correct way to access state for each parameter
        state = self.state[p]

        alpha = group['lr']
        beta1, beta2 = group['betas']
        eps = group['eps']
        weight_decay = group['weight_decay']
        t = state.get("t",1)

        alpha_t = alpha *math.sqrt((1-beta2**t)/(1-beta1**t))
        p.data -= alpha*weight_decay*p.data

        prev_mt = state.get('m',torch.zeros_like(grad))
        prev_vt = state.get('v',torch.zeros_like(grad))
        # print(prev_mt.shape,prev_vt.shape,grad.shape)
        mt = beta1*prev_mt + (1-beta1)* grad
        vt = beta2*prev_vt + (1-beta2)*(torch.square(grad))

        p.data -= alpha_t*(mt/(torch.sqrt(vt)+eps))

        state['m'] = mt
        state['v'] = vt
        state['t'] = t+1

    return loss

In [58]:
def cross_entropy_backwards(inputs, targets):
  batch_size = inputs.shape[0]
  probs = softmax(inputs).to(torch.accelerator.current_accelerator())
  probs[torch.arange(batch_size),targets] -= 1
  return probs/batch_size

def backprop(dout,X, W):
  # Changed x to X to use the local GPU tensor
  dw = dout.T @ X
  db = torch.sum(dout,dim = 0)
  dx = dout @ W

  return dw,db,dx

In [51]:
torch.cuda.device_count()

1

In [52]:
model = LinearClassification(X_train.shape[1],3).to(torch.accelerator.current_accelerator())
criterion = cross_entropy
optimizer = AdamW(model.parameters(),lr = 0.001)


In [53]:
X_tensor = torch.tensor(X_train, dtype=torch.float32).to(torch.accelerator.current_accelerator())
y_tensor = torch.tensor(y_train,dtype = torch.long).to(torch.accelerator.current_accelerator())


In [61]:
warmup_iter= 200
cosine_iter = 1500
min_learning_rate = 1e-6
max_learning_rate = 0.1

for it in range(2000):
  outputs = model(X_tensor)
  lr = get_cosine_lr(it,warmup_iter,cosine_iter,min_learning_rate,max_learning_rate)
  for g in optimizer.param_groups:
    g['lr'] = lr
  optimizer.zero_grad()
  logits = cross_entropy_backwards(outputs, y_tensor)

  dw, db, _ = backprop(logits, X_tensor, model.weight)
  model.weight.grad = dw
  model.bias.grad = db
  clip_gradient(model.parameters(), 1)
  optimizer.step()

In [62]:
outputs = model(X_tensor)

y_pred = softmax(outputs)
y_pred = torch.argmax(y_pred,dim = -1)
accuracy = (y_pred == y_tensor).sum().item()/y_tensor.shape[0]
accuracy

0.9833333333333333

In [63]:
X_test_tensor=torch.tensor(X_test,dtype = torch.float32).to(torch.accelerator.current_accelerator())
y_test_tensor = torch.tensor(y_test,dtype = torch.long).to(torch.accelerator.current_accelerator())

with torch.no_grad():
  outputs = model(X_test_tensor).to(torch.accelerator.current_accelerator())

y_pred = softmax(outputs)
y_pred = torch.argmax(y_pred,dim = -1)

accuracy = (y_pred == y_test_tensor).sum().item()/y_test_tensor.shape[0]
accuracy

0.9666666666666667